{
 "title": "Dirextalk Message Server",
 "description": "Dirextalk Message Server dashboard from https://github.com/YingSuiAI/dirextalk-message-server/",
 "tags": [
  "matrix",
  "dendrite"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(dendrite_syncapi_active_sync_requests, namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(dendrite_syncapi_active_sync_requests{namespace=~\"$namespace\"}, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Registered Users",
   "type": "stat",
   "description": "Total number of registered users",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dendrite_clientapi_reg_users_total{namespace=~\"$namespace\",service=~\"$service\"}) by (namespace,service)",
     "legendFormat": "{{namespace}}: {{service}}"
    }
   ]
  },
  {
   "title": "Sync API",
   "type": "timeseries",
   "description": "The number of sync requests that are active right now and are waiting to be woken by a notifier",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(dendrite_syncapi_active_sync_requests{namespace=~\"$namespace\",service=~\"$service\"}[$__rate_interval]))by (namspace,service)",
     "legendFormat": "active: {{namspace}} - {{service}}"
    },
    {
     "expr": "sum(rate(dendrite_syncapi_waiting_sync_requests{namespace=~\"$namespace\",service=~\"$service\"}[$__rate_interval]))by (namespace,service)",
     "legendFormat": "waiting: {{namspace}} - {{service}}"
    }
   ]
  },
  {
   "title": "Federation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Federation Sender Destination",
   "type": "timeseries",
   "description": "Collection of queues for sending transactions to other matrix servers",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dendrite_federationapi_destination_queues_running{namespace=~\"$namespace\",service=~\"$service\"}",
     "legendFormat": "Queue Running: {{namespace}}-{{service}}"
    },
    {
     "expr": "dendrite_federationapi_destination_queues_total{namespace=~\"$namespace\",service=~\"$service\"}",
     "legendFormat": "Queue Total: {{namespace}}-{{service}}"
    },
    {
     "expr": "dendrite_federationapi_destination_queues_backing_off{namespace=~\"$namespace\",service=~\"$service\"}",
     "legendFormat": "Backing Off: {{namespace}}-{{service}}"
    }
   ]
  }
 ]
}