// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.4
// source: agent_gateway.proto

package agentgatewayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentRunIngress_CreateAgentRun_FullMethodName = "/dirextalk.agent_gateway.v1.AgentRunIngress/CreateAgentRun"
)

// AgentRunIngressClient is the client API for AgentRunIngress service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentRunIngress is the narrow authenticated boundary from the Legacy Matrix
// Gateway into Agent Control. It is mounted only on the internal listener that
// requires the exact LegacyMatrixGateway mTLS service identity. The
// authenticated identity supplies the tenant; callers cannot select a tenant
// in the request.
//
// This contract carries only opaque vNext lifecycle identifiers and digests.
// Raw prompts, Matrix room IDs, Matrix event IDs, result payloads, completion,
// and failure reporting are deliberately outside this artifact. The Gateway
// maps its source timeline onto opaque ConversationId and EventId UUIDv7 values
// before calling this service.
//
// Every request and response is capped at 65536 encoded bytes. Strings use
// UTF-8 byte limits and reject C0/C1 controls. uint64 revision values are
// limited to 1..9007199254740991.
//
// Cross-language digests use this exact framing:
//
//	LP(x) = U64BE(byte_length(x)) || x
//	COMMIT(domain, parts...) = SHA-256(LP(ASCII(domain)) || LP(part1) || ...)
//
// UUID parts are the 16 RFC 4122 network-order bytes parsed from canonical
// text; integer parts are their unsigned eight-byte big-endian representation.
//
// Before this RPC, the Gateway durably claims the unique pair consisting of
// the exact Matrix room_id UTF-8 bytes and request UUID. idempotency_digest is
// COMMIT domain "dirextalk.agent-gateway-idempotency.v1" with, in order:
// authenticated tenant UUID, exact Matrix room_id UTF-8 bytes, and exact
// non-empty idempotency_key UTF-8 bytes from the invocation. Reusing that key
// with another request UUID for the same tenant and room is a conflict.
//
// request_digest is COMMIT domain
// "dirextalk.agent-gateway-run-request.v1" with, in order: authenticated tenant
// UUID, request UUID, idempotency_digest, Installation UUID, Conversation UUID,
// request Event UUID, a one-byte preferred-Connector marker (0 absent, 1
// present), preferred Connector UUID only when present, capability count
// U64BE, each required capability as a separate part in ascending UTF-8 byte
// order, dispatch enum numeric value U64BE, and grant version U64BE. The Agent
// Control server recomputes this digest and rejects a mismatch.
//
// Conformance vector: tenant 01890f00-0000-7000-8000-000000000301, room
// !legacy:example.test, and key once-01 produce idempotency digest
// 64c1af57ad01ed35ddc024958d56c8aec12405d975429f3bedb7a72af87200d3.
// With request/installation/conversation/event/Connector UUID suffixes
// 0310/0311/0312/0313/0314 respectively, capabilities chat.streaming and
// tool.read, SINGLE, and grant 4, the request digest is
// a49fbeb70ef8a0e7e1cdf1961f5873f450a22112306c52d5992be9cbfb6acf80.
type AgentRunIngressClient interface {
	CreateAgentRun(ctx context.Context, in *CreateAgentRunRequest, opts ...grpc.CallOption) (*CreateAgentRunResponse, error)
}

type agentRunIngressClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentRunIngressClient(cc grpc.ClientConnInterface) AgentRunIngressClient {
	return &agentRunIngressClient{cc}
}

func (c *agentRunIngressClient) CreateAgentRun(ctx context.Context, in *CreateAgentRunRequest, opts ...grpc.CallOption) (*CreateAgentRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAgentRunResponse)
	err := c.cc.Invoke(ctx, AgentRunIngress_CreateAgentRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentRunIngressServer is the server API for AgentRunIngress service.
// All implementations must embed UnimplementedAgentRunIngressServer
// for forward compatibility.
//
// AgentRunIngress is the narrow authenticated boundary from the Legacy Matrix
// Gateway into Agent Control. It is mounted only on the internal listener that
// requires the exact LegacyMatrixGateway mTLS service identity. The
// authenticated identity supplies the tenant; callers cannot select a tenant
// in the request.
//
// This contract carries only opaque vNext lifecycle identifiers and digests.
// Raw prompts, Matrix room IDs, Matrix event IDs, result payloads, completion,
// and failure reporting are deliberately outside this artifact. The Gateway
// maps its source timeline onto opaque ConversationId and EventId UUIDv7 values
// before calling this service.
//
// Every request and response is capped at 65536 encoded bytes. Strings use
// UTF-8 byte limits and reject C0/C1 controls. uint64 revision values are
// limited to 1..9007199254740991.
//
// Cross-language digests use this exact framing:
//
//	LP(x) = U64BE(byte_length(x)) || x
//	COMMIT(domain, parts...) = SHA-256(LP(ASCII(domain)) || LP(part1) || ...)
//
// UUID parts are the 16 RFC 4122 network-order bytes parsed from canonical
// text; integer parts are their unsigned eight-byte big-endian representation.
//
// Before this RPC, the Gateway durably claims the unique pair consisting of
// the exact Matrix room_id UTF-8 bytes and request UUID. idempotency_digest is
// COMMIT domain "dirextalk.agent-gateway-idempotency.v1" with, in order:
// authenticated tenant UUID, exact Matrix room_id UTF-8 bytes, and exact
// non-empty idempotency_key UTF-8 bytes from the invocation. Reusing that key
// with another request UUID for the same tenant and room is a conflict.
//
// request_digest is COMMIT domain
// "dirextalk.agent-gateway-run-request.v1" with, in order: authenticated tenant
// UUID, request UUID, idempotency_digest, Installation UUID, Conversation UUID,
// request Event UUID, a one-byte preferred-Connector marker (0 absent, 1
// present), preferred Connector UUID only when present, capability count
// U64BE, each required capability as a separate part in ascending UTF-8 byte
// order, dispatch enum numeric value U64BE, and grant version U64BE. The Agent
// Control server recomputes this digest and rejects a mismatch.
//
// Conformance vector: tenant 01890f00-0000-7000-8000-000000000301, room
// !legacy:example.test, and key once-01 produce idempotency digest
// 64c1af57ad01ed35ddc024958d56c8aec12405d975429f3bedb7a72af87200d3.
// With request/installation/conversation/event/Connector UUID suffixes
// 0310/0311/0312/0313/0314 respectively, capabilities chat.streaming and
// tool.read, SINGLE, and grant 4, the request digest is
// a49fbeb70ef8a0e7e1cdf1961f5873f450a22112306c52d5992be9cbfb6acf80.
type AgentRunIngressServer interface {
	CreateAgentRun(context.Context, *CreateAgentRunRequest) (*CreateAgentRunResponse, error)
	mustEmbedUnimplementedAgentRunIngressServer()
}

// UnimplementedAgentRunIngressServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentRunIngressServer struct{}

func (UnimplementedAgentRunIngressServer) CreateAgentRun(context.Context, *CreateAgentRunRequest) (*CreateAgentRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAgentRun not implemented")
}
func (UnimplementedAgentRunIngressServer) mustEmbedUnimplementedAgentRunIngressServer() {}
func (UnimplementedAgentRunIngressServer) testEmbeddedByValue()                         {}

// UnsafeAgentRunIngressServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentRunIngressServer will
// result in compilation errors.
type UnsafeAgentRunIngressServer interface {
	mustEmbedUnimplementedAgentRunIngressServer()
}

func RegisterAgentRunIngressServer(s grpc.ServiceRegistrar, srv AgentRunIngressServer) {
	// If the following call panics, it indicates UnimplementedAgentRunIngressServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentRunIngress_ServiceDesc, srv)
}

func _AgentRunIngress_CreateAgentRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRunIngressServer).CreateAgentRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRunIngress_CreateAgentRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRunIngressServer).CreateAgentRun(ctx, req.(*CreateAgentRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentRunIngress_ServiceDesc is the grpc.ServiceDesc for AgentRunIngress service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentRunIngress_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dirextalk.agent_gateway.v1.AgentRunIngress",
	HandlerType: (*AgentRunIngressServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAgentRun",
			Handler:    _AgentRunIngress_CreateAgentRun_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent_gateway.proto",
}
