// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: agent_gateway.proto

package agentgatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Only explicit single dispatch and policy-authorized ordered failover are
// admitted. Broadcast, race, and workflow are not representable here.
type DispatchMode int32

const (
	DispatchMode_DISPATCH_MODE_UNSPECIFIED DispatchMode = 0
	DispatchMode_DISPATCH_MODE_SINGLE      DispatchMode = 1
	DispatchMode_DISPATCH_MODE_FAILOVER    DispatchMode = 2
)

// Enum value maps for DispatchMode.
var (
	DispatchMode_name = map[int32]string{
		0: "DISPATCH_MODE_UNSPECIFIED",
		1: "DISPATCH_MODE_SINGLE",
		2: "DISPATCH_MODE_FAILOVER",
	}
	DispatchMode_value = map[string]int32{
		"DISPATCH_MODE_UNSPECIFIED": 0,
		"DISPATCH_MODE_SINGLE":      1,
		"DISPATCH_MODE_FAILOVER":    2,
	}
)

func (x DispatchMode) Enum() *DispatchMode {
	p := new(DispatchMode)
	*p = x
	return p
}

func (x DispatchMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DispatchMode) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_gateway_proto_enumTypes[0].Descriptor()
}

func (DispatchMode) Type() protoreflect.EnumType {
	return &file_agent_gateway_proto_enumTypes[0]
}

func (x DispatchMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DispatchMode.Descriptor instead.
func (DispatchMode) EnumDescriptor() ([]byte, []int) {
	return file_agent_gateway_proto_rawDescGZIP(), []int{0}
}

type RunRoutingState int32

const (
	RunRoutingState_RUN_ROUTING_STATE_UNSPECIFIED        RunRoutingState = 0
	RunRoutingState_RUN_ROUTING_STATE_QUEUED             RunRoutingState = 1
	RunRoutingState_RUN_ROUTING_STATE_OFFERED            RunRoutingState = 2
	RunRoutingState_RUN_ROUTING_STATE_LEASED             RunRoutingState = 3
	RunRoutingState_RUN_ROUTING_STATE_RECONCILE_REQUIRED RunRoutingState = 4
	RunRoutingState_RUN_ROUTING_STATE_EXPIRED            RunRoutingState = 5
)

// Enum value maps for RunRoutingState.
var (
	RunRoutingState_name = map[int32]string{
		0: "RUN_ROUTING_STATE_UNSPECIFIED",
		1: "RUN_ROUTING_STATE_QUEUED",
		2: "RUN_ROUTING_STATE_OFFERED",
		3: "RUN_ROUTING_STATE_LEASED",
		4: "RUN_ROUTING_STATE_RECONCILE_REQUIRED",
		5: "RUN_ROUTING_STATE_EXPIRED",
	}
	RunRoutingState_value = map[string]int32{
		"RUN_ROUTING_STATE_UNSPECIFIED":        0,
		"RUN_ROUTING_STATE_QUEUED":             1,
		"RUN_ROUTING_STATE_OFFERED":            2,
		"RUN_ROUTING_STATE_LEASED":             3,
		"RUN_ROUTING_STATE_RECONCILE_REQUIRED": 4,
		"RUN_ROUTING_STATE_EXPIRED":            5,
	}
)

func (x RunRoutingState) Enum() *RunRoutingState {
	p := new(RunRoutingState)
	*p = x
	return p
}

func (x RunRoutingState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunRoutingState) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_gateway_proto_enumTypes[1].Descriptor()
}

func (RunRoutingState) Type() protoreflect.EnumType {
	return &file_agent_gateway_proto_enumTypes[1]
}

func (x RunRoutingState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunRoutingState.Descriptor instead.
func (RunRoutingState) EnumDescriptor() ([]byte, []int) {
	return file_agent_gateway_proto_rawDescGZIP(), []int{1}
}

type CreateAgentRunRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RequestId            string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                                                        // Canonical lowercase UUIDv7 text.
	IdempotencyDigest    []byte                 `protobuf:"bytes,2,opt,name=idempotency_digest,json=idempotencyDigest,proto3" json:"idempotency_digest,omitempty"`                                // Exactly 32 domain-separated SHA-256 bytes.
	RequestDigest        []byte                 `protobuf:"bytes,3,opt,name=request_digest,json=requestDigest,proto3" json:"request_digest,omitempty"`                                            // Exactly 32 domain-separated SHA-256 bytes.
	InstallationId       string                 `protobuf:"bytes,4,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`                                         // Canonical lowercase UUIDv7 text.
	ConversationId       string                 `protobuf:"bytes,5,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`                                         // Opaque canonical lowercase UUIDv7 text; never a Matrix room ID.
	RequestEventId       string                 `protobuf:"bytes,6,opt,name=request_event_id,json=requestEventId,proto3" json:"request_event_id,omitempty"`                                       // Opaque canonical lowercase UUIDv7 text; never a Matrix event ID.
	PreferredConnectorId *string                `protobuf:"bytes,7,opt,name=preferred_connector_id,json=preferredConnectorId,proto3,oneof" json:"preferred_connector_id,omitempty"`               // Canonical lowercase UUIDv7 text when present.
	RequiredCapabilities []string               `protobuf:"bytes,8,rep,name=required_capabilities,json=requiredCapabilities,proto3" json:"required_capabilities,omitempty"`                       // At most 64 unique stable names, each 1..128 bytes.
	DispatchMode         DispatchMode           `protobuf:"varint,9,opt,name=dispatch_mode,json=dispatchMode,proto3,enum=dirextalk.agent_gateway.v1.DispatchMode" json:"dispatch_mode,omitempty"` // UNSPECIFIED is invalid.
	GrantVersion         uint64                 `protobuf:"varint,10,opt,name=grant_version,json=grantVersion,proto3" json:"grant_version,omitempty"`                                             // Positive JSON-safe integer.
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateAgentRunRequest) Reset() {
	*x = CreateAgentRunRequest{}
	mi := &file_agent_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentRunRequest) ProtoMessage() {}

func (x *CreateAgentRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentRunRequest.ProtoReflect.Descriptor instead.
func (*CreateAgentRunRequest) Descriptor() ([]byte, []int) {
	return file_agent_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAgentRunRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CreateAgentRunRequest) GetIdempotencyDigest() []byte {
	if x != nil {
		return x.IdempotencyDigest
	}
	return nil
}

func (x *CreateAgentRunRequest) GetRequestDigest() []byte {
	if x != nil {
		return x.RequestDigest
	}
	return nil
}

func (x *CreateAgentRunRequest) GetInstallationId() string {
	if x != nil {
		return x.InstallationId
	}
	return ""
}

func (x *CreateAgentRunRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *CreateAgentRunRequest) GetRequestEventId() string {
	if x != nil {
		return x.RequestEventId
	}
	return ""
}

func (x *CreateAgentRunRequest) GetPreferredConnectorId() string {
	if x != nil && x.PreferredConnectorId != nil {
		return *x.PreferredConnectorId
	}
	return ""
}

func (x *CreateAgentRunRequest) GetRequiredCapabilities() []string {
	if x != nil {
		return x.RequiredCapabilities
	}
	return nil
}

func (x *CreateAgentRunRequest) GetDispatchMode() DispatchMode {
	if x != nil {
		return x.DispatchMode
	}
	return DispatchMode_DISPATCH_MODE_UNSPECIFIED
}

func (x *CreateAgentRunRequest) GetGrantVersion() uint64 {
	if x != nil {
		return x.GrantVersion
	}
	return 0
}

type CreateAgentRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                                                           // Exact accepted request ID.
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`                                                                       // Canonical lowercase UUIDv7 text.
	Inserted      bool                   `protobuf:"varint,3,opt,name=inserted,proto3" json:"inserted,omitempty"`                                                                             // False only for an exact idempotent replay.
	RoutingState  RunRoutingState        `protobuf:"varint,4,opt,name=routing_state,json=routingState,proto3,enum=dirextalk.agent_gateway.v1.RunRoutingState" json:"routing_state,omitempty"` // Current durable state, including replay advancement.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAgentRunResponse) Reset() {
	*x = CreateAgentRunResponse{}
	mi := &file_agent_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentRunResponse) ProtoMessage() {}

func (x *CreateAgentRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentRunResponse.ProtoReflect.Descriptor instead.
func (*CreateAgentRunResponse) Descriptor() ([]byte, []int) {
	return file_agent_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAgentRunResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CreateAgentRunResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *CreateAgentRunResponse) GetInserted() bool {
	if x != nil {
		return x.Inserted
	}
	return false
}

func (x *CreateAgentRunResponse) GetRoutingState() RunRoutingState {
	if x != nil {
		return x.RoutingState
	}
	return RunRoutingState_RUN_ROUTING_STATE_UNSPECIFIED
}

var File_agent_gateway_proto protoreflect.FileDescriptor

const file_agent_gateway_proto_rawDesc = "" +
	"\n" +
	"\x13agent_gateway.proto\x12\x1adirextalk.agent_gateway.v1\"\x87\x04\n" +
	"\x15CreateAgentRunRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12-\n" +
	"\x12idempotency_digest\x18\x02 \x01(\fR\x11idempotencyDigest\x12%\n" +
	"\x0erequest_digest\x18\x03 \x01(\fR\rrequestDigest\x12'\n" +
	"\x0finstallation_id\x18\x04 \x01(\tR\x0einstallationId\x12'\n" +
	"\x0fconversation_id\x18\x05 \x01(\tR\x0econversationId\x12(\n" +
	"\x10request_event_id\x18\x06 \x01(\tR\x0erequestEventId\x129\n" +
	"\x16preferred_connector_id\x18\a \x01(\tH\x00R\x14preferredConnectorId\x88\x01\x01\x123\n" +
	"\x15required_capabilities\x18\b \x03(\tR\x14requiredCapabilities\x12M\n" +
	"\rdispatch_mode\x18\t \x01(\x0e2(.dirextalk.agent_gateway.v1.DispatchModeR\fdispatchMode\x12#\n" +
	"\rgrant_version\x18\n" +
	" \x01(\x04R\fgrantVersionB\x19\n" +
	"\x17_preferred_connector_id\"\xbc\x01\n" +
	"\x16CreateAgentRunResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1a\n" +
	"\binserted\x18\x03 \x01(\bR\binserted\x12P\n" +
	"\rrouting_state\x18\x04 \x01(\x0e2+.dirextalk.agent_gateway.v1.RunRoutingStateR\froutingState*c\n" +
	"\fDispatchMode\x12\x1d\n" +
	"\x19DISPATCH_MODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14DISPATCH_MODE_SINGLE\x10\x01\x12\x1a\n" +
	"\x16DISPATCH_MODE_FAILOVER\x10\x02*\xd8\x01\n" +
	"\x0fRunRoutingState\x12!\n" +
	"\x1dRUN_ROUTING_STATE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18RUN_ROUTING_STATE_QUEUED\x10\x01\x12\x1d\n" +
	"\x19RUN_ROUTING_STATE_OFFERED\x10\x02\x12\x1c\n" +
	"\x18RUN_ROUTING_STATE_LEASED\x10\x03\x12(\n" +
	"$RUN_ROUTING_STATE_RECONCILE_REQUIRED\x10\x04\x12\x1d\n" +
	"\x19RUN_ROUTING_STATE_EXPIRED\x10\x052\x8a\x01\n" +
	"\x0fAgentRunIngress\x12w\n" +
	"\x0eCreateAgentRun\x121.dirextalk.agent_gateway.v1.CreateAgentRunRequest\x1a2.dirextalk.agent_gateway.v1.CreateAgentRunResponseb\x06proto3"

var (
	file_agent_gateway_proto_rawDescOnce sync.Once
	file_agent_gateway_proto_rawDescData []byte
)

func file_agent_gateway_proto_rawDescGZIP() []byte {
	file_agent_gateway_proto_rawDescOnce.Do(func() {
		file_agent_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_gateway_proto_rawDesc), len(file_agent_gateway_proto_rawDesc)))
	})
	return file_agent_gateway_proto_rawDescData
}

var file_agent_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_agent_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_agent_gateway_proto_goTypes = []any{
	(DispatchMode)(0),              // 0: dirextalk.agent_gateway.v1.DispatchMode
	(RunRoutingState)(0),           // 1: dirextalk.agent_gateway.v1.RunRoutingState
	(*CreateAgentRunRequest)(nil),  // 2: dirextalk.agent_gateway.v1.CreateAgentRunRequest
	(*CreateAgentRunResponse)(nil), // 3: dirextalk.agent_gateway.v1.CreateAgentRunResponse
}
var file_agent_gateway_proto_depIdxs = []int32{
	0, // 0: dirextalk.agent_gateway.v1.CreateAgentRunRequest.dispatch_mode:type_name -> dirextalk.agent_gateway.v1.DispatchMode
	1, // 1: dirextalk.agent_gateway.v1.CreateAgentRunResponse.routing_state:type_name -> dirextalk.agent_gateway.v1.RunRoutingState
	2, // 2: dirextalk.agent_gateway.v1.AgentRunIngress.CreateAgentRun:input_type -> dirextalk.agent_gateway.v1.CreateAgentRunRequest
	3, // 3: dirextalk.agent_gateway.v1.AgentRunIngress.CreateAgentRun:output_type -> dirextalk.agent_gateway.v1.CreateAgentRunResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_agent_gateway_proto_init() }
func file_agent_gateway_proto_init() {
	if File_agent_gateway_proto != nil {
		return
	}
	file_agent_gateway_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_gateway_proto_rawDesc), len(file_agent_gateway_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_gateway_proto_goTypes,
		DependencyIndexes: file_agent_gateway_proto_depIdxs,
		EnumInfos:         file_agent_gateway_proto_enumTypes,
		MessageInfos:      file_agent_gateway_proto_msgTypes,
	}.Build()
	File_agent_gateway_proto = out.File
	file_agent_gateway_proto_goTypes = nil
	file_agent_gateway_proto_depIdxs = nil
}
